# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:34
from __future__ import unicode_literals

from django.db import migrations, ProgrammingError
from architect.commands import partition


def create_partition(apps, schema_editor):
    try:
        path = 'event.models'
        partition.run(dict(module=path))
    except ProgrammingError:
        # Possibly because models were just un-migrated or
        # fields have been changed that effect Architect
        print("Unable to apply partitions for module '{}'".format(path))
    else:
        print("Applied partitions for module '{}'".format(path))


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_partition),
    ]
